"""initial schema

Revision ID: b468f0d754c8
Revises: 
Create Date: 2026-05-24 16:02:17.056818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b468f0d754c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('icono', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'carrera', name='uk_materia_carrera'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('docente', 'estudiante'), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('idx_email', ['email'], unique=False)
        batch_op.create_index('idx_rol', ['rol'], unique=False)

    op.create_table('agentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=10), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('s3_prefix', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia_id', 'docente_id', name='uk_materia_docente'),
    sa.UniqueConstraint('s3_prefix'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('agentes', schema=None) as batch_op:
        batch_op.create_index('idx_docente', ['docente_id'], unique=False)
        batch_op.create_index('idx_materia', ['materia_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('tamano_kb', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agente_id', 'nombre', name='uk_agente_nombre'),
    sa.UniqueConstraint('s3_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('idx_agente_orden', ['agente_id', 'orden'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('idx_agente_orden')

    op.drop_table('skills')
    with op.batch_alter_table('agentes', schema=None) as batch_op:
        batch_op.drop_index('idx_materia')
        batch_op.drop_index('idx_docente')

    op.drop_table('agentes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('idx_rol')
        batch_op.drop_index('idx_email')

    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
